# Generated by Django 3.1.2 on 2020-10-14 03:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_auto_20201014_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='number_of_members',
        ),
        migrations.AddField(
            model_name='group',
            name='admins',
            field=models.TextField(default='1'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GroupMember',
        ),
    ]
