# Generated by Django 3.1.2 on 2020-10-14 07:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_auto_20201014_1159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='WorkGroup',
        ),
    ]
