# Generated by Django 3.1.2 on 2020-10-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20201017_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='period',
            old_name='group',
            new_name='work_group',
        ),
    ]
