# Generated by Django 3.1.2 on 2020-10-19 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20201019_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='period',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.period'),
        ),
    ]
