# Generated by Django 3.1.2 on 2020-10-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20201019_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='blocked_out_shifts',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='blocked_out_shifts',
            field=models.ManyToManyField(related_name='blocked_out_shifts', to='main_app.Shift'),
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='preferred_shifts',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='preferred_shifts',
            field=models.ManyToManyField(related_name='preferred_shifts', to='main_app.Shift'),
        ),
    ]
